# Generated by Django 5.2 on 2025-09-27 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('annual', 'إجازة سنوية'), ('sick', 'إجازة مرضية'), ('emergency', 'إجازة طارئة'), ('maternity', 'إجازة أمومة'), ('paternity', 'إجازة أبوة'), ('unpaid', 'إجازة بدون راتب'), ('personal', 'إجازة شخصية')], max_length=20, verbose_name='نوع الإجازة')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('days_count', models.PositiveIntegerField(verbose_name='عدد الأيام')),
                ('reason', models.TextField(verbose_name='سبب الإجازة')),
                ('emergency_contact', models.CharField(blank=True, max_length=20, verbose_name='رقم الطوارئ')),
                ('status', models.CharField(choices=[('pending', 'معلق'), ('approved', 'معتمد'), ('rejected', 'مرفوض'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('manager_notes', models.TextField(blank=True, verbose_name='ملاحظات المدير')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الموافقة')),
                ('attachments', models.JSONField(default=list, help_text='قائمة بمسارات الملفات المرفقة', verbose_name='المرفقات')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL, verbose_name='وافق بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'طلب الإجازة',
                'verbose_name_plural': 'طلبات الإجازات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('annual', 'إجازة سنوية'), ('sick', 'إجازة مرضية'), ('emergency', 'إجازة طارئة'), ('maternity', 'إجازة أمومة'), ('paternity', 'إجازة أبوة')], max_length=20, verbose_name='نوع الإجازة')),
                ('total_days', models.PositiveIntegerField(default=0, verbose_name='إجمالي الأيام')),
                ('used_days', models.PositiveIntegerField(default=0, verbose_name='الأيام المستخدمة')),
                ('remaining_days', models.PositiveIntegerField(default=0, verbose_name='الأيام المتبقية')),
                ('year', models.PositiveIntegerField(verbose_name='السنة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'رصيد الإجازة',
                'verbose_name_plural': 'أرصدة الإجازات',
                'ordering': ['employee', 'leave_type', 'year'],
                'unique_together': {('employee', 'leave_type', 'year')},
            },
        ),
    ]
