# Generated by Django 5.2 on 2025-09-25 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('annual', 'إجازة سنوية'), ('sick', 'إجازة مرضية'), ('emergency', 'إجازة طارئة'), ('maternity', 'إجازة أمومة'), ('paternity', 'إجازة أبوة'), ('unpaid', 'إجازة بدون راتب'), ('other', 'أخرى')], max_length=20, verbose_name='نوع الإجازة')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('approved', 'معتمد'), ('rejected', 'مرفوض'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('reason', models.TextField(verbose_name='سبب الإجازة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الموافقة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user', verbose_name='اعتمد بواسطة')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leaves', to='users.user', verbose_name='أنشأ بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='users.user', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'إجازة',
                'verbose_name_plural': 'الإجازات',
                'ordering': ['-created_at'],
            },
        ),
    ]
