# Generated by Django 5.1.4 on 2026-03-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='attachments',
            field=models.JSONField(blank=True, default=list, help_text='قائمة بمسارات الملفات المرفقة', null=True, verbose_name='المرفقات'),
        ),
    ]
