# Generated by Django 5.2 on 2025-09-25 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المهمة')),
                ('export_type', models.CharField(choices=[('employees', 'الموظفين'), ('schedules', 'الجداول التشغيلية'), ('leaves', 'الإجازات'), ('violations', 'المخالفات'), ('reports', 'التقارير')], max_length=20, verbose_name='نوع التصدير')),
                ('file_format', models.CharField(default='excel', max_length=10, verbose_name='تنسيق الملف')),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('processing', 'قيد المعالجة'), ('completed', 'مكتمل'), ('failed', 'فشل'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='مسار الملف')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='حجم الملف')),
                ('filters', models.JSONField(default=dict, verbose_name='الفلاتر')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإكمال')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
            ],
            options={
                'verbose_name': 'مهمة تصدير',
                'verbose_name_plural': 'مهام التصدير',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المهمة')),
                ('file_path', models.CharField(max_length=500, verbose_name='مسار الملف')),
                ('file_size', models.PositiveIntegerField(verbose_name='حجم الملف')),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('processing', 'قيد المعالجة'), ('completed', 'مكتمل'), ('failed', 'فشل'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('total_rows', models.PositiveIntegerField(default=0, verbose_name='إجمالي الصفوف')),
                ('processed_rows', models.PositiveIntegerField(default=0, verbose_name='الصفوف المعالجة')),
                ('success_rows', models.PositiveIntegerField(default=0, verbose_name='الصفوف الناجحة')),
                ('error_rows', models.PositiveIntegerField(default=0, verbose_name='الصفوف الخاطئة')),
                ('errors', models.JSONField(default=list, verbose_name='الأخطاء')),
                ('mapping', models.JSONField(default=dict, verbose_name='خريطة الحقول')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإكمال')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
            ],
            options={
                'verbose_name': 'مهمة استيراد',
                'verbose_name_plural': 'مهام الاستيراد',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم التكامل')),
                ('integration_type', models.CharField(choices=[('hr_system', 'نظام الموارد البشرية'), ('payroll', 'نظام الرواتب'), ('attendance', 'نظام الحضور والانصراف'), ('external_api', 'API خارجي'), ('file_import', 'استيراد ملفات')], max_length=20, verbose_name='نوع التكامل')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('inactive', 'غير نشط'), ('error', 'خطأ'), ('maintenance', 'تحت الصيانة')], default='inactive', max_length=20, verbose_name='الحالة')),
                ('configuration', models.JSONField(default=dict, verbose_name='إعدادات التكامل')),
                ('description', models.TextField(blank=True, verbose_name='وصف التكامل')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='آخر مزامنة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
            ],
            options={
                'verbose_name': 'تكامل',
                'verbose_name_plural': 'التكاملات',
                'ordering': ['name'],
            },
        ),
    ]
