# Generated by Django 5.0 on 2025-09-29 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='معرف الكائن المرتبط')),
                ('current_step', models.PositiveIntegerField(default=1, verbose_name='الخطوة الحالية')),
                ('total_steps', models.PositiveIntegerField(verbose_name='إجمالي الخطوات')),
                ('status', models.CharField(choices=[('pending', 'معلق'), ('in_progress', 'قيد المراجعة'), ('approved', 'معتمد'), ('rejected', 'مرفوض'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الموافقة')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='سبب الرفض')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_flows', to=settings.AUTH_USER_MODEL, verbose_name='وافق بواسطة')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='نوع الكائن المرتبط')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_approval_flows', to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
            ],
            options={
                'verbose_name': 'مسار الموافقة',
                'verbose_name_plural': 'مسارات الموافقات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.PositiveIntegerField(verbose_name='ترتيب الخطوة')),
                ('required_role', models.CharField(max_length=50, verbose_name='الدور المطلوب')),
                ('status', models.CharField(choices=[('pending', 'معلق'), ('approved', 'معتمد'), ('rejected', 'مرفوض'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('action', models.CharField(blank=True, choices=[('approve', 'موافقة'), ('reject', 'رفض'), ('cancel', 'إلغاء'), ('request_changes', 'طلب تعديل')], max_length=20, verbose_name='الإجراء')),
                ('comment', models.TextField(blank=True, verbose_name='تعليق')),
                ('acted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإجراء')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('approval_flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='approvals.approvalflow', verbose_name='مسار الموافقة')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_approval_steps', to=settings.AUTH_USER_MODEL, verbose_name='مُعيَّن لـ')),
            ],
            options={
                'verbose_name': 'خطوة الموافقة',
                'verbose_name_plural': 'خطوات الموافقات',
                'ordering': ['step_order'],
                'unique_together': {('approval_flow', 'step_order')},
            },
        ),
    ]
