# Generated by Django 5.2 on 2025-09-25 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='معرف الكائن')),
                ('approval_type', models.CharField(choices=[('schedule', 'جدول تشغيلي'), ('leave', 'إجازة'), ('violation', 'مخالفة'), ('employee', 'موظف'), ('branch', 'فرع'), ('other', 'أخرى')], max_length=20, verbose_name='نوع الموافقة')),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('approved', 'معتمد'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('comments', models.TextField(blank=True, verbose_name='تعليقات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الموافقة')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المعتمد')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='نوع المحتوى')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_approvals', to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
            ],
            options={
                'verbose_name': 'موافقة',
                'verbose_name_plural': 'الموافقات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المسار')),
                ('flow_type', models.CharField(choices=[('schedule', 'جدول تشغيلي'), ('leave', 'إجازة'), ('violation', 'مخالفة'), ('employee', 'موظف'), ('branch', 'فرع')], max_length=20, verbose_name='نوع المسار')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('steps', models.JSONField(default=list, verbose_name='خطوات الموافقة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
            ],
            options={
                'verbose_name': 'مسار الموافقات',
                'verbose_name_plural': 'مسارات الموافقات',
                'ordering': ['name'],
            },
        ),
    ]
