# Generated by Django 5.2 on 2025-09-26 02:30

from django.conf import settings
from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='رقم الهاتف غير صحيح. يجب أن يبدأ بـ +966 أو 0 ويحتوي على 9 أرقام', regex='^(\\+966|0)?[5-9][0-9]{8}$')], verbose_name='رقم الهاتف')),
                ('role', models.CharField(choices=[('employee', 'موظف'), ('branch_manager', 'مدير معرض'), ('coordinator', 'منسق'), ('region_manager', 'مدير منطقة'), ('operations_manager', 'مدير عمليات'), ('admin_manager', 'مدير إدارة'), ('super_admin', 'مدير عام')], default='employee', max_length=20, verbose_name='الدور')),
                ('job_id', models.CharField(blank=True, max_length=50, verbose_name='الرقم الوظيفي')),
                ('work_hours', models.PositiveIntegerField(choices=[(8, '8 ساعات (6 أيام عمل)'), (9, '9 ساعات (5 أيام عمل)')], default=8, verbose_name='عدد ساعات العمل')),
                ('work_days', models.PositiveIntegerField(default=6, verbose_name='عدد أيام العمل')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('inactive', 'غير نشط'), ('suspended', 'معلق'), ('terminated', 'منتهي الخدمة')], default='active', max_length=20, verbose_name='الحالة')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='المنصب')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='القسم')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التعيين')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الراتب')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('emergency_contact', models.CharField(blank=True, max_length=100, verbose_name='جهة الاتصال في الطوارئ')),
                ('emergency_phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الطوارئ')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ملف المستخدم',
                'verbose_name_plural': 'ملفات المستخدمين',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
    ]


