# Generated by Django 5.1.4 on 2025-11-22 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='region',
            field=models.CharField(blank=True, choices=[('north', 'المنطقة الشمالية'), ('south', 'المنطقة الجنوبية'), ('east', 'المنطقة الشرقية'), ('center', 'المنطقة الوسطى'), ('west', 'المنطقة الغربية')], max_length=50, verbose_name='المنطقة'),
        ),
    ]
