# Generated by Django 5.1.4 on 2025-11-30 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_region_userprofile_managed_regions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='managed_regions',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='managed_regions',
            field=models.JSONField(blank=True, default=list, verbose_name='المناطق المُدارة'),
        ),
    ]
