# Generated by Django 4.2.11 on 2026-01-01 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_userprofile_managed_regions_delete_region_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='managed_regions',
        ),
    ]
