# Generated by Django 4.2.28 on 2026-08-15 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_managed_regions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_laborer',
            field=models.BooleanField(default=False, verbose_name='عمالة (لا تحتسب في عجز التغطية)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='work_hours',
            field=models.PositiveIntegerField(choices=[(8, '8 ساعات (يوم واحد راحة - 48 ساعة أسبوعياً)'), (9, '9 ساعات (يومان راحة - 45 ساعة أسبوعياً)'), (85, '8 ساعات عمل و5 ساعات يوم الجمعة (يوم واحد راحة - 45 ساعة أسبوعياً)')], default=8, verbose_name='نظام ساعات العمل'),
        ),
    ]
