# Generated by Django 5.2 on 2025-09-27 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('attendance', 'تأخير'), ('absence', 'غياب'), ('behavior', 'سلوك'), ('performance', 'أداء'), ('safety', 'سلامة'), ('policy', 'انتهاك سياسة')], max_length=20, verbose_name='نوع المخالفة')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('time', models.TimeField(verbose_name='الوقت')),
                ('description', models.TextField(verbose_name='وصف المخالفة')),
                ('severity', models.CharField(choices=[('low', 'منخفضة'), ('medium', 'متوسطة'), ('high', 'عالية'), ('critical', 'حرجة')], default='low', max_length=20, verbose_name='درجة الخطورة')),
                ('status', models.CharField(choices=[('pending', 'معلقة'), ('investigating', 'قيد التحقيق'), ('resolved', 'محلولة'), ('escalated', 'مرفوعة'), ('archived', 'مؤرشفة')], default='pending', max_length=20, verbose_name='الحالة')),
                ('action_taken', models.CharField(blank=True, choices=[('warning', 'تحذير'), ('notice', 'إنذار'), ('suspension', 'إيقاف'), ('termination', 'فصل'), ('training', 'تدريب'), ('counseling', 'إرشاد')], max_length=20, verbose_name='الإجراء المتخذ')),
                ('action_description', models.TextField(blank=True, verbose_name='وصف الإجراء المتخذ')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('witnesses', models.TextField(blank=True, help_text='أسماء الشهود إن وجدوا', verbose_name='الشهود')),
                ('evidence', models.JSONField(default=list, help_text='قائمة بمسارات الملفات أو الصور', verbose_name='الأدلة')),
                ('investigation_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التحقيق')),
                ('resolution_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحل')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الأرشفة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_violations', to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
                ('investigated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigated_violations', to=settings.AUTH_USER_MODEL, verbose_name='تحقق بواسطة')),
            ],
            options={
                'verbose_name': 'المخالفة',
                'verbose_name_plural': 'المخالفات',
                'ordering': ['-created_at'],
            },
        ),
    ]
