# Generated by Django 5.2 on 2025-09-25 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('attendance', 'مخالفة حضور وانصراف'), ('behavior', 'مخالفة سلوكية'), ('performance', 'مخالفة أداء'), ('safety', 'مخالفة أمان'), ('other', 'أخرى')], max_length=20, verbose_name='نوع المخالفة')),
                ('severity', models.CharField(choices=[('minor', 'بسيطة'), ('moderate', 'متوسطة'), ('major', 'كبيرة'), ('critical', 'حرجة')], max_length=20, verbose_name='درجة الخطورة')),
                ('description', models.TextField(verbose_name='وصف المخالفة')),
                ('date_occurred', models.DateTimeField(verbose_name='تاريخ وقوع المخالفة')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='مكان وقوع المخالفة')),
                ('action_taken', models.CharField(choices=[('warning', 'تحذير شفوي'), ('written_warning', 'تحذير كتابي'), ('suspension', 'إيقاف'), ('fine', 'غرامة مالية'), ('termination', 'فصل'), ('other', 'أخرى')], max_length=20, verbose_name='الإجراء المتخذ')),
                ('action_description', models.TextField(blank=True, verbose_name='وصف الإجراء')),
                ('fine_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='مبلغ الغرامة')),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('investigating', 'قيد التحقيق'), ('resolved', 'محلولة'), ('closed', 'مغلقة')], default='pending', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('witnesses', models.TextField(blank=True, verbose_name='الشهود')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الموافقة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user', verbose_name='اعتمد بواسطة')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_violations', to='users.user', verbose_name='أنشأ بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='users.user', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'مخالفة',
                'verbose_name_plural': 'المخالفات',
                'ordering': ['-created_at'],
            },
        ),
    ]
