# Generated by Django 5.2 on 2025-09-25 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم التقرير')),
                ('report_type', models.CharField(choices=[('attendance', 'تقرير الحضور والانصراف'), ('schedule', 'تقرير الجداول التشغيلية'), ('leaves', 'تقرير الإجازات'), ('violations', 'تقرير المخالفات'), ('performance', 'تقرير الأداء'), ('financial', 'تقرير مالي'), ('custom', 'تقرير مخصص')], max_length=20, verbose_name='نوع التقرير')),
                ('filters', models.JSONField(default=dict, verbose_name='الفلاتر')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('generated', 'مولد'), ('scheduled', 'مجدول'), ('failed', 'فشل')], default='draft', max_length=20, verbose_name='الحالة')),
                ('description', models.TextField(blank=True, verbose_name='وصف التقرير')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
            ],
            options={
                'verbose_name': 'تقرير',
                'verbose_name_plural': 'التقارير',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم القالب')),
                ('template_type', models.CharField(choices=[('attendance', 'قالب الحضور والانصراف'), ('schedule', 'قالب الجداول التشغيلية'), ('leaves', 'قالب الإجازات'), ('violations', 'قالب المخالفات'), ('performance', 'قالب الأداء'), ('financial', 'قالب مالي')], max_length=20, verbose_name='نوع القالب')),
                ('settings', models.JSONField(default=dict, verbose_name='إعدادات القالب')),
                ('description', models.TextField(blank=True, verbose_name='وصف القالب')),
                ('is_default', models.BooleanField(default=False, verbose_name='القالب الافتراضي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
            ],
            options={
                'verbose_name': 'قالب تقرير',
                'verbose_name_plural': 'قوالب التقارير',
                'ordering': ['name'],
            },
        ),
    ]
