# Generated by Django 5.2 on 2025-09-27 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الفرع')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='كود الفرع')),
                ('type', models.CharField(choices=[('main', 'الفرع الرئيسي'), ('branch', 'فرع فرعي'), ('warehouse', 'مستودع'), ('office', 'مكتب')], max_length=20, verbose_name='نوع الفرع')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('inactive', 'غير نشط'), ('maintenance', 'تحت الصيانة')], default='active', max_length=20, verbose_name='الحالة')),
                ('address', models.TextField(verbose_name='العنوان')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='المدينة')),
                ('region', models.CharField(choices=[('riyadh', 'الرياض'), ('makkah', 'مكة المكرمة'), ('eastern', 'المنطقة الشرقية'), ('asir', 'عسير'), ('jazan', 'جازان'), ('medina', 'المدينة المنورة'), ('qassim', 'القصيم'), ('hail', 'حائل'), ('tabuk', 'تبوك'), ('northern', 'الحدود الشمالية'), ('jazan', 'جازان'), ('najran', 'نجران'), ('albaha', 'الباحة'), ('jouf', 'الجوف')], max_length=50, verbose_name='المنطقة')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='الرمز البريدي')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('capacity', models.PositiveIntegerField(default=1, verbose_name='السعة الاستيعابية')),
                ('opening_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الافتتاح')),
                ('working_days', models.JSONField(default=list, help_text='قائمة بأيام العمل مثل ["saturday", "sunday", "monday"]', verbose_name='أيام العمل')),
                ('description', models.TextField(blank=True, verbose_name='وصف الفرع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_branches', to=settings.AUTH_USER_MODEL, verbose_name='مدير الفرع')),
            ],
            options={
                'verbose_name': 'الفرع',
                'verbose_name_plural': 'الفروع',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BranchShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الشفت')),
                ('start_time', models.TimeField(verbose_name='ساعة البداية')),
                ('end_time', models.TimeField(verbose_name='ساعة النهاية')),
                ('break_start', models.TimeField(blank=True, null=True, verbose_name='ساعة بداية الاستراحة')),
                ('break_end', models.TimeField(blank=True, null=True, verbose_name='ساعة نهاية الاستراحة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='branches.branch', verbose_name='الفرع')),
            ],
            options={
                'verbose_name': 'شفت الفرع',
                'verbose_name_plural': 'شفتات الفروع',
                'ordering': ['start_time'],
                'unique_together': {('branch', 'name')},
            },
        ),
    ]
