# Generated by Django 5.2 on 2025-09-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='category',
            field=models.CharField(choices=[('A', 'الفئة أ'), ('B', 'الفئة ب'), ('C', 'الفئة ج'), ('D', 'الفئة د')], default='B', max_length=1, verbose_name='فئة الفرع'),
        ),
    ]
