# Generated by Django 4.2.11 on 2026-01-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_branch_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchshift',
            name='days',
            field=models.JSONField(blank=True, default=list, help_text='قائمة بالأيام التي ينطبق عليها الشفت (اتركه فارغاً لينطبق على جميع أيام عمل الفرع)', verbose_name='أيام الشفت'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='region',
            field=models.CharField(choices=[('north', 'المنطقة الشمالية'), ('south', 'المنطقة الجنوبية'), ('east', 'المنطقة الشرقية'), ('center', 'المنطقة الوسطى'), ('west', 'المنطقة الغربية')], max_length=50, verbose_name='المنطقة'),
        ),
    ]
