# Generated by Django 5.2.2 on 2025-10-07 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(help_text='سيتم إنشاؤه تلقائياً إذا لم يتم تحديده', max_length=50, unique=True, verbose_name='الرقم الوظيفي')),
                ('job_title', models.CharField(max_length=100, verbose_name='المسمى الوظيفي')),
                ('employment_type', models.CharField(choices=[('full_time', 'دوام كامل'), ('part_time', 'دوام جزئي'), ('contract', 'عقد'), ('temporary', 'مؤقت')], default='full_time', max_length=20, verbose_name='نوع التوظيف')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('inactive', 'غير نشط'), ('suspended', 'معلق'), ('terminated', 'منتهي الخدمة')], default='active', max_length=20, verbose_name='الحالة')),
                ('hire_date', models.DateField(verbose_name='تاريخ التعيين')),
                ('termination_date', models.DateField(blank=True, null=True, verbose_name='تاريخ إنهاء الخدمة')),
                ('work_location', models.CharField(blank=True, max_length=200, verbose_name='مكان العمل')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('direct_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_employees', to=settings.AUTH_USER_MODEL, verbose_name='المدير المباشر')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'الموظف',
                'verbose_name_plural': 'الموظفين',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('contract', 'عقد العمل'), ('id_copy', 'صورة الهوية'), ('certificate', 'شهادة'), ('cv', 'السيرة الذاتية'), ('other', 'أخرى')], max_length=20, verbose_name='نوع الوثيقة')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الوثيقة')),
                ('file', models.FileField(upload_to='employee_documents/%Y/%m/', verbose_name='الملف')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employees.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'وثيقة الموظف',
                'verbose_name_plural': 'وثائق الموظفين',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeEmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('relationship', models.CharField(choices=[('spouse', 'الزوج/الزوجة'), ('parent', 'الوالد/الوالدة'), ('sibling', 'الأخ/الأخت'), ('child', 'الابن/الابنة'), ('friend', 'صديق'), ('other', 'أخرى')], max_length=20, verbose_name='العلاقة')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('is_primary', models.BooleanField(default=False, verbose_name='جهة اتصال أساسية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='employees.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'جهة الاتصال في الطوارئ',
                'verbose_name_plural': 'جهات الاتصال في الطوارئ',
                'ordering': ['-is_primary', 'name'],
            },
        ),
    ]
