# Generated by Django 5.2.2 on 2025-10-07 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_number',
            field=models.CharField(blank=True, help_text='سيتم إنشاؤه تلقائياً إذا لم يتم تحديده', max_length=50, unique=True, verbose_name='الرقم الوظيفي'),
        ),
    ]
