# Generated by Django 5.2 on 2025-09-25 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الجدول')),
                ('schedule_type', models.CharField(choices=[('weekly', 'أسبوعي'), ('monthly', 'شهري'), ('quarterly', 'ربع سنوي'), ('yearly', 'سنوي')], max_length=20, verbose_name='نوع الجدول')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('pending_coordinator', 'في انتظار موافقة المنسق'), ('pending_region_manager', 'في انتظار موافقة مدير المنطقة'), ('pending_operations_manager', 'في انتظار موافقة مدير العمليات'), ('pending_admin_manager', 'في انتظار موافقة مدير الإدارة'), ('approved', 'معتمد'), ('rejected', 'مرفوض'), ('active', 'نشط'), ('completed', 'مكتمل')], default='draft', max_length=30, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch', verbose_name='الفرع')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user', verbose_name='أنشأ بواسطة')),
            ],
            options={
                'verbose_name': 'جدول تشغيلي',
                'verbose_name_plural': 'الجداول التشغيلية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('coordinator', 'منسق'), ('region_manager', 'مدير المنطقة'), ('operations_manager', 'مدير العمليات'), ('admin_manager', 'مدير الإدارة')], max_length=20, verbose_name='مستوى الموافقة')),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('approved', 'معتمد'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('comments', models.TextField(blank=True, verbose_name='تعليقات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الموافقة')),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user', verbose_name='المعتمد')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='schedules.schedule', verbose_name='الجدول')),
            ],
            options={
                'verbose_name': 'موافقة الجدول',
                'verbose_name_plural': 'موافقات الجداول',
                'ordering': ['level', 'created_at'],
                'unique_together': {('schedule', 'level')},
            },
        ),
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='users.user', verbose_name='الموظف')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='schedules.schedule', verbose_name='الجدول')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.shift', verbose_name='الشفت')),
            ],
            options={
                'verbose_name': 'دخول الجدول',
                'verbose_name_plural': 'دخول الجداول',
                'ordering': ['date', 'shift__start_time'],
                'unique_together': {('schedule', 'employee', 'shift', 'date')},
            },
        ),
    ]
