# Generated by Django 5.2 on 2025-09-27 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_type', models.CharField(choices=[('weekly', 'أسبوعي'), ('monthly', 'شهري'), ('quarterly', 'ربع سنوي'), ('yearly', 'سنوي')], default='weekly', max_length=20, verbose_name='نوع الجدول')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('pending_coordinator', 'في انتظار موافقة المنسق'), ('pending_region_manager', 'في انتظار موافقة مدير المنطقة'), ('pending_operations_manager', 'في انتظار موافقة مدير العمليات'), ('pending_admin_manager', 'في انتظار موافقة مدير الإدارة'), ('approved', 'معتمد'), ('rejected', 'مرفوض'), ('active', 'نشط'), ('completed', 'مكتمل')], default='draft', max_length=30, verbose_name='الحالة')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='الإصدار')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch', verbose_name='الفرع')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
            ],
            options={
                'verbose_name': 'الجدول التشغيلي',
                'verbose_name_plural': 'الجداول التشغيلية',
                'ordering': ['-created_at'],
                'unique_together': {('branch', 'start_date', 'end_date', 'version')},
            },
        ),
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('start_time', models.TimeField(verbose_name='ساعة البداية')),
                ('end_time', models.TimeField(verbose_name='ساعة النهاية')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='عدد الساعات')),
                ('is_cover', models.BooleanField(default=False, verbose_name='تغطية')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='schedules.schedule', verbose_name='الجدول')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branchshift', verbose_name='الشفت')),
            ],
            options={
                'verbose_name': 'إدخال الجدول التشغيلي',
                'verbose_name_plural': 'إدخالات الجداول التشغيلية',
                'ordering': ['date', 'start_time'],
                'unique_together': {('schedule', 'employee', 'date', 'shift')},
            },
        ),
    ]
